home:
    resource: "@AssoBundle/Controller/Front"
    type:     annotation

adhesion:
    resource: "@AssoBundle/Controller/Front"
    type:     annotation

shop:
    resource: "@AssoBundle/Controller/Front"
    type:     annotation

admin:
    resource: "@AssoBundle/Controller/Backend"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
